export const RUT_PHASES = {
    INIT: 'INIT',
    WAIT_BODY: 'WAIT_BODY',
    WAIT_DV: 'WAIT_DV',
    CONFIRM: 'CONFIRM',
    COMPLETE: 'COMPLETE',
    ERROR: 'ERROR',
    LISTEN_RUT: 'LISTEN_RUT',
    PROCESS_RUT: 'PROCESS_RUT'
};
